UI-MVC/Models/DTO/Project/NewProjectDto.cs
using System;
using System.Collections.Generic;
using COI.BL.Domain.Project;
using Microsoft.AspNetCore.Http;

namespace COI.UI.MVC.Models.DTO.Project
{
	public class NewProjectDto
	{
		public string Title { get; set; }
		
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }

		public int OrganisationId { get; set; }
		
		public List<string> Texts { get; set; }
		public List<IFormFile> Images { get; set; }
		public List<IFormFile> Videos { get; set; }
		public List<string> Locations { get; set; }
		public List<string> Links { get; set; }

		public NewProjectDto()
		{
			this.Texts = new List<string>();
			this.Images = new List<IFormFile>();
			this.Videos = new List<IFormFile>();
			this.Locations = new List<string>();
			this.Links = new List<string>();
		}
	}
}

UI-MVC/Models/DTO/Project/NewProjectPhaseDto.cs
using System;
using COI.BL.Domain.Project;

namespace COI.UI.MVC.Models.DTO.Project
{
	public class NewProjectPhaseDto
	{
		public string Title { get; set; }
		public string Description { get; set; }
		
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }

		public int ProjectId { get; set; }
	}
}

UI-MVC/Models/DTO/Project/ProjectDto.cs
using System;
using System.Collections.Generic;
using COI.BL.Domain.Project;
using COI.UI.MVC.Models.DTO.Ideation;

namespace COI.UI.MVC.Models.DTO.Project
{
	public class ProjectDto
	{
		public int ProjectId { get; set; }
		
		public string Title { get; set; }
		
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }
		
		public ProjectState ProjectState { get; set; }
		public List<FieldDto> Fields { get; set; }
		public int OrganisationId { get; set; }
		public List<ProjectPhaseDto> ProjectPhases { get; set; }
	}
}

UI-MVC/Models/DTO/Project/ProjectMinDto.cs
using System;
using System.Collections.Generic;
using COI.BL.Domain.Project;
using COI.UI.MVC.Models.DTO.Ideation;

namespace COI.UI.MVC.Models.DTO.Project
{
	public class ProjectMinDto
	{
		public int ProjectId { get; set; }
		
		public string Title { get; set; }
		
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }
		
		public ProjectState ProjectState { get; set; }
		public List<FieldDto> Fields { get; set; }
		
		public List<ProjectPhaseMinDto> ProjectPhases { get; set; }
		public int OrganisationId { get; set; }
	}
}

UI-MVC/Models/DTO/Project/ProjectPhaseDto.cs
using System;
using System.Collections.Generic;
using COI.BL.Domain.Project;
using COI.UI.MVC.Models.DTO.Ideation;
using COI.UI.MVC.Models.DTO.Questionnaire;

namespace COI.UI.MVC.Models.DTO.Project
{
	public class ProjectPhaseDto
	{
		public int ProjectPhaseId { get; set; }
		
		public string Title { get; set; }
		public string Description { get; set; }
		
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }
		
		public ProjectState State { get; set; }

		public int ProjectId { get; set; }

		public List<IdeationDto> Ideations { get; set; }
		public List<QuestionnaireDto> Questionnaires { get; set; }
	}
}

UI-MVC/Models/DTO/Project/ProjectPhaseMinDto.cs
using System;
using COI.BL.Domain.Project;

namespace COI.UI.MVC.Models.DTO.Project
{
	public class ProjectPhaseMinDto
	{
		public int ProjectPhaseId { get; set; }
		
		public string Title { get; set; }
		public string Description { get; set; }
		
		public DateTime StartDate { get; set; }
		public DateTime EndDate { get; set; }
		
		public ProjectState ProjectState { get; set; }

		public int ProjectId { get; set; }
	}
}

UI-MVC/Controllers/IdeationController.cs
using System.Collections.Generic;
using System.Security.Claims;
using COI.BL.Domain.Ideation;
using COI.BL.Domain.User;
using COI.BL.Ideation;
using COI.UI.MVC.Authorization;
using COI.UI.MVC.Helpers;
using COI.UI.MVC.Models.DTO.Demo;
using COI.UI.MVC.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
    [Authorize(Policy = AuthConstants.AdminPolicy)]
	[Route("{orgId}/[controller]")]
	public class IdeationController : Controller
	{
		private readonly IIdeationManager _ideationManager;
		private readonly IIdeasHelper _ideasHelper;
		private readonly SignInManager<User> _signInManager;

		public IdeationController(IIdeationManager ideationManager, IIdeasHelper ideasHelper, SignInManager<User> signInManager)
		{
			_ideationManager = ideationManager;
			_ideasHelper = ideasHelper;
			_signInManager = signInManager;
		}
		
		[HttpGet]
        [Route("Details/{id}")]
		[AllowAnonymous]
		public IActionResult Details(int id)
		{
			string userId = null;
			if (_signInManager.IsSignedIn(User))
			{
				userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
			}
			Ideation ideation = _ideationManager.GetIdeation(id);
			var ideas = _ideasHelper.GetIdeas(userId, ideation.IdeationId);
			
			Dictionary<int, SAVotes> ideaVotes = new Dictionary<int, SAVotes>();

			foreach (var idea in ideas)
			{
				var anVotes = 0;
				var veVotes = 0;
				var usVotes = 0;
				var realIdea = _ideationManager.GetIdea(idea.IdeaId);
				foreach (var vote in realIdea.Votes)
				{
					if (vote.User != null)
					{
						usVotes += vote.Value;
					} else if (vote.Email != null)
					{
						veVotes += vote.Value;
					}
					else
					{
						anVotes += vote.Value;
					}
				}
				ideaVotes.Add(realIdea.IdeaId, new SAVotes()
				{
					anVotes = anVotes,
					veVotes = veVotes,
					usVotes = usVotes
				});
			}
			
			var model = new IdeationUserVote
			{
				ideas = ideas,
				ideation = ideation,
				ideaVotes = ideaVotes
			};
			return View(model);
		}
		
		[Route("Create/{phaseId}")]
		public IActionResult Create(int phaseId)
		{
			return View(phaseId);
		}
	}
}

UI-MVC/Controllers/ProjectController.cs
using System.Collections.Generic;
using System.Linq;
using COI.BL.Domain.Project;
using COI.BL.Project;
using COI.UI.MVC.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
    [Authorize(Policy = AuthConstants.AdminPolicy)]
    [Route("{orgId}/[controller]")]
    public class ProjectController : Controller
    {
        private readonly IProjectManager _projectManager;

        public ProjectController(IProjectManager projectManager)
        {
            _projectManager = projectManager;
        }
        
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index([FromQuery] bool open, [FromQuery] bool showLimited, [FromRoute] string orgId)
        {
	        IEnumerable<Project> projects = null;
	        if (!showLimited)
	        {
		        projects = _projectManager.GetLastNProjects(orgId, 6).ToList();
	        }
	        else
	        {
		        ProjectState projectStateShown = open ? ProjectState.Open : ProjectState.Closed;
		        projects = _projectManager.GetLastNProjects(orgId, 6, projectStateShown).ToList();
	        }
	        ViewBag.open = open;
	        ViewBag.showLimited = showLimited;
            return View(projects);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("Details/{id}")]
        public IActionResult Details(int id)
        {
            Project project = _projectManager.GetProject(id);
            return View(project);
        }

		[Route("Create")]
	    public IActionResult Create()
        {
	        return View();
        }

		[Route("CreatePhase/{projectId}")]
        public IActionResult CreatePhase(int projectId)
        {
	        return View(projectId);
        }
    }
}

UI-MVC/Controllers/ProjectsController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using COI.BL.Domain.Project;
using COI.BL.Domain.User;
using COI.BL.Project;
using COI.UI.MVC.Models;
using COI.UI.MVC.Models.DTO.Ideation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
    [Authorize(AuthenticationSchemes = JwtConstants.AuthSchemes)]
    public class ProjectsController : Controller
    {
        private readonly IProjectManager _projectManager;
        private readonly IMapper _mapper;

        public ProjectsController(IProjectManager projectManager, IMapper mapper)
        {
            _projectManager = projectManager;
            _mapper = mapper;
        }
        
        public IActionResult Index()
        {
            IEnumerable<Project> projects = _projectManager.GetProjects().ToList();
            return View(projects);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            Project project = _projectManager.GetProject(id);
            return View(project);
        }

//        [Authorize(Roles=["test"])]
//		TODO: Authorization
        public IActionResult Create()
        {
	        return View();
        }

        public IActionResult CreatePhase()
        {
	        return View();
        }
    }
}

UI-MVC/Controllers/QuestionnaireController.cs
using System.Collections.Generic;
using COI.BL.Domain.Questionnaire;
using COI.BL.Questionnaire;
using COI.UI.MVC.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
	[Route("{orgId}/[controller]")]
    [Authorize(Policy = AuthConstants.AdminPolicy)]
	public class QuestionnaireController : Controller
	{
		private readonly IQuestionnaireManager _questionnaireManager;

		public QuestionnaireController(IQuestionnaireManager questionnaireManager)
		{
			_questionnaireManager = questionnaireManager;
		}
		
		[AllowAnonymous]
		public IActionResult Index()
		{
			IEnumerable<Questionnaire> questionnaires = _questionnaireManager.GetQuestionnaires();
			return View(questionnaires);
		}
		
		[HttpGet]
		[Route("Details/{id}")]
		[AllowAnonymous]
		public IActionResult Details(int id)
		{
			Questionnaire questionnaire = _questionnaireManager.GetQuestionnaire(id);
			return View(questionnaire);
		}
		
		[HttpGet]
		[Route("Results/{id}")]
		[AllowAnonymous]
		public IActionResult Results(int id)
		{
			Questionnaire questionnaire = _questionnaireManager.GetQuestionnaire(id);
			return View(questionnaire);
		}

		[HttpGet]
		[Route("Thanks")]
		[AllowAnonymous]
		public IActionResult Thanks([FromQuery] string qId)
		{
			ViewBag.questionnaireId = qId;
			return View();
		}
		
		[HttpGet]
		[Route("Create/{phaseId}")]
		public IActionResult Create(int phaseId)
		{
			return View(phaseId);
		}
	}
}

UI-MVC/Controllers/api/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Castle.Core.Internal;
using COI.BL;
using COI.BL.Domain.Ideation;
using COI.BL.Domain.Project;
using COI.BL.Ideation;
using COI.BL.Organisation;
using COI.BL.Project;
using COI.UI.MVC.Authorization;
using COI.UI.MVC.Helpers;
using COI.UI.MVC.Models;
using COI.UI.MVC.Models.DTO.Project;
using COI.UI.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers.api
{
    [Authorize(Policy = AuthConstants.AdminPolicy)]
    [Authorize(AuthenticationSchemes = AuthenticationConstants.AuthSchemes)]
	[ApiController]
	[Route("api/{orgId}/[controller]")]
	public class ProjectsController : ControllerBase
	{
		private readonly IMapper _mapper;
		private readonly IProjectManager _projectManager;
		private readonly IIdeationManager _ideationManager;
		private readonly IOrganisationManager _organisationManager;
		private readonly IUnitOfWorkManager _unitOfWorkManager;
		private readonly IFileService _fileService;

		private readonly IProjectPhasesHelper _projectPhasesHelper;

		public ProjectsController(IMapper mapper, IProjectManager projectManager, IIdeationManager ideationManager, IOrganisationManager organisationManager, IUnitOfWorkManager unitOfWorkManager, IFileService fileService, IProjectPhasesHelper projectPhasesHelper)
		{
			_mapper = mapper;
			_projectManager = projectManager;
			_ideationManager = ideationManager;
			_organisationManager = organisationManager;
			_unitOfWorkManager = unitOfWorkManager;
			_fileService = fileService;
			_projectPhasesHelper = projectPhasesHelper;
		}

		[AllowAnonymous]
		[HttpGet]
		public IActionResult GetProjects(
			string orgId,
			[FromQuery(Name = "limit")] int numberOfProjectsToGet, 
			[FromQuery(Name = "state")] string stateString)
		{
			IEnumerable<Project> projs = null;
            bool stateValid = Enum.TryParse(stateString, true, out ProjectState state);
            
			if (numberOfProjectsToGet != 0)
			{
				if (stateValid)
				{
                    projs = _projectManager.GetLastNProjects(
	                    orgId,
                        numberOfProjectsToGet, state
                        ).ToList();
				}
				else
				{
                    projs = _projectManager.GetLastNProjects(
	                    orgId,
                        numberOfProjectsToGet
                        ).ToList();
				}
			}
			else
			{
				projs = _projectManager.GetProjects(orgId).ToList();
			}
			
			var response = _mapper.Map<List<ProjectMinDto>>(projs);

			return Ok(response);
		}

		[AllowAnonymous]
		[HttpGet("last")]
		public IActionResult GetLastProject(string orgId, [FromQuery(Name = "state")] string stateString)
		{
			Project ret = null;
			if (!stateString.IsNullOrEmpty())
			{
                bool stateValid = Enum.TryParse(stateString, true, out ProjectState state);
                if (!stateValid)
                {
                    return BadRequest("Project state invalid.");
                }

                ret = _projectManager.GetLastNProjects(orgId, 1, state).FirstOrDefault();
			}
			else
			{
				ret = _projectManager.GetLastNProjects(orgId, 1).FirstOrDefault();
			}

			if (ret == null)
			{
				return BadRequest("No projects found for the current criteria.");
			}

			return Ok(_mapper.Map<ProjectMinDto>(ret));
		}
		
		[AllowAnonymous]
		[HttpGet("{id}")]
		public IActionResult GetProject(int id)
		{
			try
			{
				var proj = _projectManager.GetProject(id);
				if (proj == null)
				{
					return NotFound("Project not found.");
				}

				return Ok(_mapper.Map<ProjectDto>(proj));
			}
			catch (Exception e)
			{
				return BadRequest($"Something went wrong in getting the project: {e.Message}.");
			}
		}
		
		[AllowAnonymous]
		[HttpGet("{id}/projectPhases")]
		public IActionResult GetPhasesForProject(int id, [FromQuery] string userId)
		{
			return Ok(_projectPhasesHelper.GetProjectPhases(id, userId));
		}
		
		[HttpPost]
		public async Task<IActionResult> PostNewProject([FromForm]NewProjectDto newProj, [FromRoute] string orgId)
		{
			try
			{
				_unitOfWorkManager.StartUnitOfWork();
				
				Project p = _projectManager.AddProject(
					newProj.Title, 
					newProj.StartDate, 
					newProj.EndDate, 
					newProj.OrganisationId);
				
				foreach (var video in newProj.Videos)
				{
					string imgLocation = await _fileService.ConvertFileToLocation(video);
					_ideationManager.AddFieldToProject(FieldType.Video, imgLocation, p.ProjectId);
				}

				foreach (var image in newProj.Images)
				{
					string imgLocation = await _fileService.ConvertFileToLocation(image);
					_ideationManager.AddFieldToProject(FieldType.Picture, imgLocation, p.ProjectId);
				}

				foreach (var textfield in newProj.Texts)
				{
					_ideationManager.AddFieldToProject(FieldType.Text, textfield, p.ProjectId);
				}
				
				foreach (var location in newProj.Locations)
				{
					_ideationManager.AddFieldToProject(FieldType.Location, location, p.ProjectId);
				}

				foreach (var link in newProj.Links)
				{
					_ideationManager.AddFieldToProject(FieldType.Link, link, p.ProjectId);
				}
				
				_unitOfWorkManager.EndUnitOfWork();

				return CreatedAtAction(
					"GetProject", 
					new {orgId, id = p.ProjectId},
					_mapper.Map<ProjectDto>(p));
			}
			catch (ValidationException ve)
			{
				return UnprocessableEntity($"Invalid input data: {ve.ValidationResult.ErrorMessage}");
			}
			catch (Exception e)
			{
				return BadRequest($"Something went wrong in creating the project: {e.Message}.");
			}
		}
		
		[HttpPut("{id}")]
		public IActionResult UpdateProject(int id, NewProjectDto updatedValues)
		{
			try
			{
				_unitOfWorkManager.StartUnitOfWork();
				Project updatedProject = _projectManager.ChangeProject(
					id, 
					updatedValues.Title,
					updatedValues.StartDate, 
					updatedValues.EndDate, 
					updatedValues.OrganisationId);
				_unitOfWorkManager.EndUnitOfWork();

				if (updatedProject == null)
				{
					return BadRequest("Something went wrong while updating the project.");
				}

				return Ok(_mapper.Map<ProjectDto>(updatedProject));
			}
			catch (ValidationException ve)
			{
				return UnprocessableEntity($"Invalid input data: {ve.ValidationResult.ErrorMessage}");
			}
			catch (ArgumentException e)
			{
				switch (e.ParamName)
				{
					case "id":
						return NotFound(e.Message);
					case "organisationId":
						return UnprocessableEntity(e.Message);
					default:
						return BadRequest(e.Message);
				}
			}
		}
	}
}

UI-MVC/Views/Project/Create.cshtml
<div class="container">
    <form method="post" class="editor mt-10" id="project_create">
        <h2 clas="mb-2">Maak een project aan</h2>
        
        <ul class="form__errors"></ul>
        
        <div class="form-group">
            <label for="project-title">Titel</label>
            <input required class="form-control" type="text" name="title" id="project-title">
        </div>
        <div class="form-group">
            <label for="project-start-date">Startdatum</label>
            <input required class="form-control" type="date" name="startDate" id="project-start-date">
        </div>
        <div class="form-group">
            <label for="project-end-date">Einddatum</label>
            <input required class="form-control" type="date" name="endDate" id="project-end-date">
        </div>

        <div class="editor__text-container mt-4">
            <div class="editor__options">
                <div class="editor__option editor__option--image">
                    <i class="material-icons">add_photo_alternate</i>
                    Foto toevoegen
                </div>
                <div class="editor__option editor__option--video">
                    <i class="material-icons">video_call</i>
                    Video toevoegen
                </div>
            </div>

            <textarea
                name="text"
                class="editor__text textbox"
                placeholder="Project beschrijving"
            ></textarea>
        </div>

        <div class="editor__images"></div>
        <div class="editor__videos"></div>

        <input
            type="file"
            class="editor__file-upload editor__file-upload--image"
            accept="image/x-png,image/gif,image/jpeg"
        />
        <input
            type="file"
            class="editor__file-upload editor__file-upload--video"
        />
        <button type="submit" class="btn editor__submit mt-2">
            Project aanmaken
        </button>
    </form>
</div>

@section Scripts
{
    <script type="text/javascript" src="/dist/project.entry.js" defer></script>
}

UI-MVC/Views/Project/CreatePhase.cshtml
@model int

<section class="content container">
    <h1 class="mb-5">Projectfase aanmaken</h1>
    <form id="phase_create">
        <ul class="form__errors"></ul>
        
        <div class="form-group">
            <label for="projectPhase-title">Titel</label>
            <input required type="text" name="title" id="projectPhase-title" class="form-control">
        </div>
        <div class="form-group">
            <label for="projectPhase-description">Beschrijving</label>
            <textarea required name="description" id="projectPhase-description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label for="projectPhase-start">Startdatum</label>
            <input required type="date" name="startDate" id="projectPhase-start" class="form-control">
        </div>
        <div class="form-group">
            <label for="projectPhase-end">Einddatum</label>
            <input required type="date" name="endDate" id="projectPhase-end" class="form-control">
        </div>
        <button type="submit" class="btn">Create</button>
    </form>
</section>

@section Scripts
{
    <script >
        const projectId = @Model;
    </script>
    <script type="text/javascript" src="/dist/project.entry.js" defer></script>
}

UI-MVC/Views/Project/Details.cshtml
@using COI.BL.Domain.Ideation
@using COI.BL.Domain.User
@using COI.UI.MVC.Helpers
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject IFieldHelper FieldHelper
@inject IOrganisationsHelper OrganisationsHelper;
@model COI.BL.Domain.Project.Project

@{
    ViewData["Title"] = Model.Title;
    var orgId = OrganisationsHelper.GetOrganisationIdentifier();
}

<section
    class="hero hero__project"
    style="background-image: url('@FieldHelper.GetFirstOfType(Model.Fields, FieldType.Picture).Content')"
>
    <div class="hero__container">
        <h1 class="hero__title">
            @Model.Title
        </h1>
    </div>
</section>
<div class="w-100 d-inline-flex">
    <div class="projectomschrijving">
        <div class="periodeDatum">
            @Model.StartDate.ToString("dd/MM/yyyy") - @Model.EndDate.ToString("dd/MM/yyyy")
        </div>
        @foreach (var field in Model.Fields)
        {
            @if (field.FieldType.Equals(FieldType.Text))
             {
                 @field.Content
             }
        }
    </div>
    @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("Superadmin")))
    {
        <div class="padding-t1rem createprojectphase">
            <a asp-controller="Project" asp-action="CreatePhase" asp-route-projectId="@Model.ProjectId" asp-route-orgId="@orgId" class="btn btn--org">Projectfase aanmaken</a>
        </div>
    }
</div>


<div id="accordion" class="inklapbaar_fase">
    @foreach (var projectPhase in Model.ProjectPhases)
    {
        <div class="card">
            <div class="card-header" id="headingOne">
                <div class="card-button">
                    <button
                        class="btn btn-link btn__witteAchtergrond btn__fase"
                        data-toggle="collapse"
                        data-target="@("#projectPhase" + projectPhase.ProjectPhaseId)"
                        aria-expanded="true"
                        aria-controls="@("projectPhase" + projectPhase.ProjectPhaseId)">
                        @projectPhase.Title
                    </button>
                    <span class="datumTot">Tot @projectPhase.EndDate.ToString("dd/MM/yyyy")</span>
                </div>
            </div>

            <div
                id="@("projectPhase" + projectPhase.ProjectPhaseId)"
                class="collapse @(projectPhase.EndDate > DateTime.Now && projectPhase.StartDate < DateTime.Now ? "show" : "")"
                aria-labelledby="headingOne"
                data-parent="#accordion">
                <div class="card-body">
                    @foreach (var ideation in projectPhase.Ideations)
                    {
                        <a asp-controller="Ideation" asp-action="Details" asp-route-orgId="@orgId" asp-route-id="@ideation.IdeationId" class="ideation">
                            <h2 class="pphase-child__title">
                                <i class="far fa-comment"></i> @ideation.Title
                            </h2>
                            <p class="pphase-child__text">
                                @FieldHelper.GetAllText(ideation.Fields)
                            </p>
                        </a>
                    }
                    
                    @foreach (var questionnaire in projectPhase.Questionnaires)
                    {
                        <a asp-controller="Questionnaire" asp-action="Details" asp-route-orgId="@orgId" asp-route-id="@questionnaire.QuestionnaireId" class="ideation">
                            <h2 class="pphase-child__title">
                                <i class="far fa-file-alt"></i> @questionnaire.Title
                            </h2>
                            <p class="pphase-child__text">
                                @questionnaire.Description
                            </p>
                        </a>
                    }
                    @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("Superadmin")))
                    {
                        <a asp-controller="Ideation" asp-action="Create" asp-route-phaseId="@projectPhase.ProjectPhaseId" asp-route-orgId="@orgId" class="ideation">
                            <h2 class="pphase-child__title mb-3">
                                <i class="fas fa-plus-circle"></i> Voeg ideation toe
                            </h2>
                        </a>
                        <a asp-controller="Questionnaire" asp-action="Create" asp-route-phaseId="@projectPhase.ProjectPhaseId" asp-route-orgId="@orgId" class="ideation">
                            <h2 class="pphase-child__title mb-3">
                                <i class="fas fa-plus-circle"></i> Voeg vragenlijst toe
                            </h2>
                        </a>
                    }
                </div>
            </div>
        </div>
    }
</div>

UI-MVC/Views/Project/Index.cshtml
@model System.Collections.Generic.IEnumerable<COI.BL.Domain.Project.Project>
@using COI.BL.Domain.Ideation
@using COI.BL.Domain.User
@using COI.UI.MVC.Helpers
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject IFieldHelper FieldHelper;
@inject IOrganisationsHelper OrganisationsHelper;

@{
    ViewBag.Title = "Overzicht";
    Layout = "_Layout";
    var orgId = OrganisationsHelper.GetOrganisationIdentifier();
    var open = ViewBag.open;
    var showLimited = ViewBag.showLimited;
}
<main class="content content--shadow container">

    <div class="d-inline-flex w-100 ">
        <div class="form-group dd_project">
            <select name="dropdownFase" class="dd_project1" id="project_statedropdown">
                <option selected="@(!showLimited)" value="all" class="keuze">Alle projecten</option>
                <option selected="@(open && showLimited)" value="open" class="keuze">Open projecten</option>
                <option selected="@(!open && showLimited)" value="closed" class="keuze">Gesloten projecten</option>
            </select>
        </div>

        @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin") || User.IsInRole("Superadmin")))
        {
            <div class="create-project__container">
                <a asp-controller="Project" asp-action="Create" asp-route-orgId="@OrganisationsHelper.GetOrganisationIdentifier()" class="btn btn--org create-project">Project aanmaken</a>
            </div>
        }
    </div>


    <div class="card-list mb-4">
        @foreach (var project in Model)
        {
            <div class="card">
                <img src="@FieldHelper.GetFirstOfType(project.Fields, FieldType.Picture).Content" alt="" class="card-img-top"/>
                <div class="card-body">
                    <h2 class="card-title">@project.Title</h2>
                    <p class="card-text">
                        @FieldHelper.GetAllText(project.Fields)
                    </p>
                </div>
                <div class="card-footer card-footer--invis">
                    <a asp-controller="Project" asp-action="Details" asp-route-orgId="@OrganisationsHelper.GetOrganisationIdentifier()" asp-route-id="@project.ProjectId" class="btn btn--org">Geef jouw mening</a>
                </div>
            </div>
        }
    </div>
</main>

@section Scripts
{
    <script type="text/javascript" src="/dist/project.entry.js" defer></script>
}