UI-MVC/Models/ViewModels/Editor.cs
using System.Collections;

namespace COI.UI.MVC.Models
{
	public class Editor
	{
		public Editor()
		{
			LoginRequired = true;
		}
		
		public string Type { get; set; }
		public string FormId { get; set; }
		public bool LoginRequired { get; set; }
	}
}

UI-MVC/Controllers/ManagementController.cs
using System;
using COI.BL.Organisation;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
	[Route("{orgId}/[controller]")]
	public class ManagementController : Controller
	{
		private readonly IOrganisationManager _organisationManager;

		public ManagementController(IOrganisationManager organisationManager)
		{
			_organisationManager = organisationManager;
		}
		
		[HttpGet]
		public IActionResult Organisation()
		{
			return View();
		}
		
		[HttpGet]
		[Route("NewOrganisation")]
		public IActionResult NewOrganisation()
		{
			return View();
		}
	}
}

UI-MVC/Controllers/OrganisationController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using COI.BL.Domain.Project;
using COI.BL.Project;
using COI.UI.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
	[Route("{orgId}/[controller]")]
    public class OrganisationController : Controller
    {
        private readonly IProjectManager _projectManager;

        public OrganisationController(IProjectManager projectManager)
        {
            _projectManager = projectManager;
        }
        
        [HttpGet]
        public IActionResult Index([FromRoute] string orgId)
        {
            IEnumerable<Project> projects = _projectManager.GetLastNProjects(orgId, 6).ToList();
            return View(projects);
        }

        [HttpGet]
        [Route("/Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

    }
}

UI-MVC/Controllers/ProjectController.cs
using System.Collections.Generic;
using System.Linq;
using COI.BL.Domain.Project;
using COI.BL.Project;
using COI.UI.MVC.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace COI.UI.MVC.Controllers
{
    [Authorize(Policy = AuthConstants.AdminPolicy)]
    [Route("{orgId}/[controller]")]
    public class ProjectController : Controller
    {
        private readonly IProjectManager _projectManager;

        public ProjectController(IProjectManager projectManager)
        {
            _projectManager = projectManager;
        }
        
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index([FromQuery] bool open, [FromQuery] bool showLimited, [FromRoute] string orgId)
        {
	        IEnumerable<Project> projects = null;
	        if (!showLimited)
	        {
		        projects = _projectManager.GetLastNProjects(orgId, 6).ToList();
	        }
	        else
	        {
		        ProjectState projectStateShown = open ? ProjectState.Open : ProjectState.Closed;
		        projects = _projectManager.GetLastNProjects(orgId, 6, projectStateShown).ToList();
	        }
	        ViewBag.open = open;
	        ViewBag.showLimited = showLimited;
            return View(projects);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("Details/{id}")]
        public IActionResult Details(int id)
        {
            Project project = _projectManager.GetProject(id);
            return View(project);
        }

		[Route("Create")]
	    public IActionResult Create()
        {
	        return View();
        }

		[Route("CreatePhase/{projectId}")]
        public IActionResult CreatePhase(int projectId)
        {
	        return View(projectId);
        }
    }
}

UI-MVC/Views/Shared/_AuthModals.cshtml
<!-- LoginModal -->
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="LoginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content login-popup">
            <div class="modal-body login-popup-body">
                <div class="row popup__row">
                    <div class="popup__afbeeldingkolom col-md-6">
                        <section
                            class="popup__afbeelding"
                            style="background-image: url('/img/antwerp.jpeg')"
                        ></section>
                    </div>
                    <div class="popup__container col-md-6 col-sm-12">
                        <form id="auth_login">
                            <h1 class="paginatitel paginatitel__popup mb-4">Log in</h1>
                            <ul class="form__errors"></ul>
                            <input
                                required
                                type="email"
                                name="email"
                                class="form__inputfield form__inputfield2 form__popupEmail form-control"
                                placeholder="Email"
                            />
                            <input
                                required
                                type="password"
                                name="password"
                                class="form__inputfield form__inputfield2 form__popupWachtwoord form-control"
                                placeholder="Wachtwoord"
                            />
                            <button class="btn btn__witteAchtergrond btn__popupLogin" type="submit">
                                Log In
                            </button>
                            <div class="login-popup__vergeten">
                                <a asp-area="Identity" asp-page="/Account/ForgotPassword">
                                    Wachtwoord vergeten?
                                </a>
                            </div>
                        </form>
                        <form asp-area="Identity" asp-page="/Account/ExternalLogin" asp-route-returnUrl="@Context.Request.Path" method="post">
                            <button class="btn btn__witteAchtergrond btn__popupFacebook"
                                    type="submit" name="provider" value="Facebook">
                                <i class="fab fa-facebook-f popup__icoon" id="fb"></i>
                                <span class="login-popup__facebook">Log in met Facebook</span>
                            </button>
                            <button class="btn btn__witteAchtergrond btn__popupGoogle"
                                    type="submit" name="provider" value="Google">
                                <i
                                    class="fab fa-google popup__icoon popup_icoonGoogle"
                                    id="google"
                                ></i>
                                <span class="login-popup__google">Log in met Google</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /LoginModal -->


<!-- RegisterModal -->
<div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="RegisterModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content login-popup">
            <div class="modal-body">
                <div class="row popup__row">
                    <div class="popup__afbeeldingkolom col-md-6">
                        <section
                            class="popup__afbeelding"
                            id="registreer-popup__afbeelding"
                            style="background-image: url('/img/antwerp.jpeg')">
                        </section>
                    </div>
                    <form class="login-popup__container col-md-6 col-sm-12 mt-5" id="auth_register">
                        <h1 class="paginatitel paginatitel__popup paginatitel__popup__registreren mb-4">Registreren</h1>
                        
                        <ul class="form__errors"></ul>

                        <div id="div1" class="hide input__organisatie">
                            <input
                                type="text"
                                class="registreer-popup__organisatie-input form-control"
                                class="registreer-popup__organisatie-input form-control"
                                id="organisatie-inputveld"
                                placeholder="Organisatie"/>
                        </div>

                        <div class="form__inputfield form__inputfield2">
                            <div class="row">
                                <div class="col">
                                    <input
                                        required
                                        type="text"
                                        name="first_name"
                                        class="form-control inputvoornaam"
                                        placeholder="Voornaam"/>
                                </div>
                                <div class="col">
                                    <input
                                        required
                                        type="text"
                                        name="last_name"
                                        class="form-control inputachternaam"
                                        placeholder="Achternaam"/>
                                </div>
                            </div>
                        </div>

                        <div class="form__inputfield form__inputfield2">
                            <div class="row">
                                <div class="col">
                                    <input 
                                        required
                                        type="date" 
                                        name="birthdate"
                                        id="birthdate"
                                        class="form-control"
                                        placeholder="yyyy-mm-dd">
                                </div>
                                <div class="col">
                                    <input
                                        type="text"
                                        name="zip"
                                        class="form-control inputpostcode"
                                        placeholder="Postcode"/>
                                </div>
                            </div>
                        </div>

                        <select name="gender" class="custom-select selectGeslacht">
                            <option selected>Geslacht</option>
                            <option value="male">Man</option>
                            <option value="female">Vrouw</option>
                        </select>

                        <input
                            required
                            type="text"
                            name="email"
                            class="form__inputfield form__inputfield2 form-control"
                            placeholder="E-mailadres"/>
                        
                        <div class="form__inputfield form__inputfield2">
                            <div class="row">
                                <div class="col">
                                    <input
                                        required
                                        type="password"
                                        name="password"
                                        class="form-control inputwachtwoord"
                                        placeholder="Wachtwoord"/>
                                </div>
                                <div class="col">
                                    <input
                                        required
                                        type="password"
                                        name="password_re"
                                        class="form-control inputherhaalwachtwoord"
                                        placeholder="Herhaal wachtwoord"/>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn__witteAchtergrond btn__popupLogin">
                            Registreer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /RegisterModal -->

UI-MVC/Views/Shared/_Editor.cshtml
@using COI.BL.Domain.User
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager
@inject SignInManager<User> SignInManager
@model COI.UI.MVC.Models.Editor

@if (!Model.LoginRequired || SignInManager.IsSignedIn(User))
{
    <!-- Editor -->
    <form method="post" class="editor mt-10" id="@Model.FormId">
        <h2 clas="mb-2">Plaats jouw @Model.Type</h2>

        <div class="editor__text-container">
            <div class="editor__options">
                <div class="editor__option editor__option--image">
                    <i class="material-icons">add_photo_alternate</i>
                    Foto toevoegen
                </div>
                @* <div class="editor__option editor__option--image"> *@
                @*     <i class="material-icons">add_location</i> *@
                @*     Locatie toevoegen *@
                @* </div> *@
                <div class="editor__option editor__option--video">
                    <i class="material-icons">video_call</i>
                    Video toevoegen
                </div>
            </div>

            <textarea
                name="text"
                class="editor__text textbox"
                placeholder="Schrijf een reactie"
            ></textarea>
        </div>

        <div class="editor__images"></div>
        <div class="editor__videos"></div>

        <input
            type="file"
            class="editor__file-upload editor__file-upload--image"
            accept="image/x-png,image/gif,image/jpeg"/>
        <input
            type="file"
            class="editor__file-upload editor__file-upload--video"/>

        <button type="submit" class="btn editor__submit mt-2">
            @Model.Type plaatsen
        </button>
    </form>
    <!-- /Editor -->
}
else
{
    <!-- Log in -->
    <section class="editor mt-10">
        <h2>Login om een @Model.Type te plaatsen</h2>
        
        <button class="btn" data-toggle="modal" data-target="#LoginModal">Log in</button>
        <button class="btn" data-toggle="modal" data-target="#RegisterModal">Maak een account</button>
    </section>
    <!-- /Log in -->
}

UI-MVC/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#d11f38">
<meta name="apple-mobile-web-app-title" content="City of Ideas">
<meta name="application-name" content="City of Ideas">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

UI-MVC/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using AutoMapper
@using COI.BL.Domain.User
@using COI.BL.Project
@using COI.UI.MVC.Authorization
@using COI.UI.MVC.Helpers
@using COI.UI.MVC.Models.DTO.Organisation
@using Microsoft.AspNetCore.Identity
@using Newtonsoft.Json
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IProjectManager ProjectManager
@inject IOrganisationsHelper OrganisationHelper;
@inject IMapper Mapper;

@{
    var organisation = OrganisationHelper.GetOrganisation();
}

<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - City of Ideas</title>
    @Html.Partial("_Favicons")

    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:300,400,600,700" rel="stylesheet" />
    <script type="module" src="~/dist/site.entry.js" defer></script>
    <link rel="stylesheet" href="~/dist/site.css">
</head>

<body>

<!-- HEADER -->
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" id="organisation" asp-controller="Home" asp-action="Index" style="color: @organisation.Color !important;" >@organisation.Name</a>
    
    @if (OrganisationHelper.HasOrganisation())
    {
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Organisation" asp-action="Index" asp-route-orgId="@organisation.Identifier">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Project" asp-action="Index" asp-route-orgId="@organisation.Identifier">Projecten</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Contact" asp-action="Index" asp-route-orgId="@organisation.Identifier">Contact</a>
                </li>
                @if (SignInManager.IsSignedIn(User) && (User.IsInRole(AuthConstants.Admin) || User.IsInRole(AuthConstants.Superadmin) || User.IsInRole(AuthConstants.Moderator)))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Management" asp-action="Organisation" asp-route-orgId="@organisation.Identifier">Manage</a>
                    </li>
                }
            </ul>

            <partial name="_LoginPartial"/>
        </div>
    }
</nav>
<!-- /HEADER -->
@* <partial name="_CookieConsentPartial"/> *@

<!-- The Modal -->
<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content werk">
        <input class="search__input" type="text" placeholder="ZOEK" />
        <i class="fas fa-search zoekModal"></i>
    </div>
</div>
<!-- /Header -->

@RenderBody()



<!-- Footer -->
<footer class="site-footer">
    <div class="site-footer__container container">
        <div class="site-footer__top-row">
            <!-- Footer-projects -->
            <div class="site-footer__projects">
                <h3 class="title--light">Projecten</h3>
                <ul>
                    @{
                        // TODO get orgId
                        var footerProjects = ProjectManager.GetLastNProjects("districtantwerpen", 3).ToList();
                    }
                    @foreach (var project in footerProjects)
                    {
                        <li><a href="">@project.Title</a></li>
                    }
                </ul>
            </div>
            <!-- /Footer-projects -->

            <!-- Footer-about -->
            <div class="site-footer__about ">
                <h3 class="title--light">Tree company</h3>
                Tree company is gespecialiseerd in de begeleiding van online participatietrajecten en het opzetten van online tools voor maatschappelijke projecten.
            </div>
            <!-- /Footer-about -->

            <!-- Footer-social-media -->
            <div class="site-footer__social-media">
                <h3 class="title--light">Follow us</h3>
                <a href="https://twitter.com/treecomp" class="text-decoration-none">
                    <i class="fab fa-twitter"></i>
                </a>
                <a
                    href="https://www.facebook.com/treecompany.be/"
                    class="text-decoration-none">
                    <i class="fab fa-facebook"></i>
                </a>
            </div>
            <!-- /Footer-social-media -->
        </div>

        <!-- Footer-terms -->
        <div class="site-footer__terms">
            <span>
                <a href="">Terms of Use</a>
            </span>
            <span>
                <a asp-controller="Organisation" asp-action="Privacy">Privacy Policy</a>
            </span>
        </div>
        <!-- /Footer-terms -->

        <!-- Footer-copyright -->
        <div class="site-footer__copyright">
            <a href="">
                <div>&copy; 2019 The tree company.</div>
                <div>All rights reserved</div>
            </a>
        </div>
        <!-- /Footer-copyright -->
    </div>
</footer>
<!-- /Footer -->

@if (!SignInManager.IsSignedIn(User))
{
    <partial name="_AuthModals"/>
    
}

@* The following code is only used for Demo purposes *@

 <div class="demo-helper" style="position: fixed; bottom: 50px; right: 50px;"> 
     <div style="font-size: 50px; color: white; background-color: darkred; padding: 7px 45px 10px; font-weight: bold; border-radius: 10px;"> 
         @{
             string role;
             try
             {
                 var userId = User.FindFirstValue(ClaimTypes.Name);
                 var user = userId != null ? await UserManager.FindByEmailAsync(userId) : null;
                 var roles = (await UserManager.GetRolesAsync(user));
                 role = user != null ? roles[0] : "Anonymous";
             }
             catch (Exception e)
             {
                 role = "Anonymous";
             }
                 
         } 
         @if (role != null) 
         { 
             @foreach (var single in role) 
             { 
                 @single 
             } 
         } 
         else 
         { 
             <p>Test</p> 
         } 
     </div> 
 </div> 

<script >
    @{
        NoRefOrganisationDto jsObj = Mapper.Map<NoRefOrganisationDto>(organisation);
        string orgJson = JsonConvert.SerializeObject(jsObj);
    }
    const organisation = @Html.Raw(orgJson);
</script>
@RenderSection("Scripts", required: false)
</body>
</html>